# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-27 02:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apiv2', '0003_auto_20180527_0217'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('lon', models.DecimalField(decimal_places=6, max_digits=9)),
                ('comment', models.TextField()),
                ('document', models.FileField(upload_to='report/media')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report', to=settings.AUTH_USER_MODEL)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apiv2.ReportTag')),
            ],
        ),
        migrations.RemoveField(
            model_name='rating',
            name='reporter',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='tag',
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
