# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-27 02:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiv2', '0004_auto_20180527_0218'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='document',
            new_name='photo',
        ),
    ]
