# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-27 02:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiv2', '0005_auto_20180527_0234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='photo',
            field=models.FileField(upload_to=b''),
        ),
    ]
