# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-27 02:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiv2', '0006_auto_20180527_0240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='tag',
        ),
    ]
