# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-27 02:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiv2', '0007_remove_report_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='tag',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='apiv2.ReportTag'),
            preserve_default=False,
        ),
    ]
