# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-27 05:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiv2', '0008_report_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tag', to='apiv2.ReportTag'),
        ),
    ]
