# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-27 05:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiv2', '0009_auto_20180527_0550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='tag',
        ),
    ]
